title: "Seth D. Thorn — CV"
description: "Academic CV for Seth D. Thorn, Arizona State University"
baseurl: ""
url: ""  # set to https://USERNAME.github.io/REPO after pushing
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: "1..3"
plugins:
  - jekyll-seo-tag

# Collections (if you expand later)
collections:
  posts:
    output: false
