name: Build and Deploy GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5

      # Build Jekyll site -> _site (read-only, that's fine)
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      # Node + Puppeteer to print HTML to PDF (write to /tmp, not _site)
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Render PDF with Puppeteer (to /tmp)
        run: |
          npm i puppeteer --no-save
          node - <<'NODE'
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({ args: ['--no-sandbox','--disable-setuid-sandbox'] });
            const page = await browser.newPage();
            const url = 'file://' + process.cwd() + '/_site/index.html';
            await page.goto(url, { waitUntil: 'networkidle0' });

            // Force @media print rules from your cv.html
            await page.emulateMediaType('print');

            await page.pdf({
              path: '/tmp/cv.pdf',
