name: Build and Deploy GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5

      # Build the Jekyll site into ./_site
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      # Make _site writable (so the PDF write doesn't EACCES)
      - run: chmod -R u+w _site

      # One compact step: install puppeteer (no package.json), render to /tmp, move to _site
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Render PDF
        run: |
          npm i puppeteer --no-save
          node - <<'NODE'
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({ args: ['--no-sandbox','--disable-setuid-sandbox'] });
            const page = await browser.newPage();
            const url = 'file://' + process.cwd() + '/_site/index.html';
            await page.goto(url, { waitUntil: 'networkidle0' });
            await page.pdf({
              path: '/tmp/cv.pdf',
              format: 'Letter',
              margin: { top: '1in', right: '1in', bottom: '1in', left: '1in' },
              printBackground: true
            });
            await browser.close();
          })();
          NODE
          mv /tmp/cv.pdf _site/cv.pdf

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
