name: Build and Deploy GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5

      # Build Jekyll site -> _site (read-only, that's fine)
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      # Node + Puppeteer to print HTML to PDF (write to /tmp, not _site)
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Render PDF with Puppeteer (to /tmp)
        run: |
          npm i puppeteer --no-save
          node - <<'NODE'
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({ args: ['--no-sandbox','--disable-setuid-sandbox'] });
            const page = await browser.newPage();
            const url = 'file://' + process.cwd() + '/_site/index.html';
            await page.goto(url, { waitUntil: 'networkidle0' });
            await page.pdf({
              path: '/tmp/cv.pdf',
              format: 'Letter',
              margin: { top: '1in', right: '1in', bottom: '1in', left: '1in' },
              printBackground: true
            });
            await browser.close();
          })();
          NODE

      # Make a writable copy of the site and inject the PDF
      - name: Assemble publish folder
        run: |
          rm -rf site_out
          mkdir -p site_out
          cp -a _site/. site_out/
          mv /tmp/cv.pdf site_out/cv.pdf

      # Upload everything in site_out (includes cv.pdf)
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site_out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
